<h1 align="center">Game of Life</h1>

In [1]:
import numpy as np
import os

### This function will read the data from a text file

In [2]:
def readfile(filename):
    data = []
    file = open(filename,'r')
    lines = file.read().splitlines()
    for line in lines:
        data.append(line.split())
    data = np.array(data)
    data = data.astype('int64')
    file.close()
    return data

### This function will write the output to a text file

In [3]:
def writefile(data):
    file = open("output.txt","w")
    content  = str(data)
    file.write(content)
    file.close()

### This function will give list of neighbors position

In [4]:
def neighbors_pos(x,y,x_shape,y_shape):
    positions = []
    if x+1 < x_shape:
        if y+1 < y_shape:
            positions.append([x+1,y+1])
        if y < y_shape:
            positions.append([x+1,y])
        if y-1 >= 0 :
            positions.append([x+1,y-1])
    if y+1 < y_shape:
        if x < x_shape:
            positions.append([x,y+1])
        if x-1 >= 0 :
            positions.append([x-1,y+1])
    if x-1 >= 0:
        if y-1 >= 0:
            positions.append([x-1,y-1])
        if y < y_shape:
            positions.append([x-1,y])
    if y-1 >= 0:
        if x < x_shape:
            positions.append([x,y-1])
    return positions            

### This function will return count of alive people

In [5]:
def alive_val(neighbors,data):
    count = 0
    for i in neighbors:
        count =count+data[i[0]][i[1]]
    return count

### This function will find the next generation grid board

In [6]:
def next_generation(data):
    x_shape = data.shape[0]
    y_shape = data.shape[1]
    next_gen = np.empty([x_shape,y_shape],dtype = "int64")
    for i in range(x_shape):
        for j in range(y_shape):
            n = neighbors_pos(i,j,x_shape,y_shape)
            alive = alive_val(n,data)
            if data[i][j]== 1 and alive < 2:
                next_gen[i][j] = 0
            if data[i][j]== 1 and alive >= 2 and alive <=3 :
                next_gen[i][j] = 1
            if data[i][j]== 1 and alive > 3:
                next_gen[i][j] = 0
            if data[i][j]== 0 and alive == 3:
                next_gen[i][j] = 1
            if data[i][j]== 0 and alive !=3:
                next_gen[i][j] = 0
    return next_gen

### This function will combine all the pieces of game

In [7]:
def game_of_life():
    filename = input("Enter file name: ")
    if not os.path.isfile(filename):
        print("File does not exist")
        return
    try:
        no_gen = int(input("Enter number of generations: "))
    except ValueError:  
        print("Number of generations must be a number")
        return
    data = readfile(filename)
    print("\nNumber of Generations = ",no_gen)
    print("Data :\n",data)
    for i in range(no_gen):
        data = next_generation(data)
    writefile(data)
    print("output :\n",data)

In [8]:
game_of_life()

Enter file name: data.txt
Enter number of generations: 5

Number of Generations =  5
Data :
 [[0 1 0 0]
 [0 0 1 0]
 [1 1 1 1]
 [0 0 0 0]]
output :
 [[0 0 0 0]
 [0 1 1 0]
 [1 0 0 1]
 [0 1 1 0]]
